apiVersion: skaffold/v2beta25
kind: Config
metadata:
  name: test
build:
  artifacts:
    - image: localhost:5000/test-client
      context: .
      jib: {}


deploy:
  kubectl:
    manifests:
      - "k8s/deployment.yml"


portForward:
  - resourceType: deployment
    resourceName: test-client
    namespace: default
    port: 8080
    localPort: 8080